tests - Change asan=1 to also exclude injected setgid failure test

diff --git a/tests/t19 b/tests/t19
--- a/tests/t19
+++ b/tests/t19
@@ -117,15 +117,15 @@ test_rawhide "$rh -M0 -X 'true' ."                         ""                   
 # On OpenBSD, setuid/setgid bits don't change euid/egid
 if [ "`uname`" != OpenBSD -a "`whoami`" = root ] && grep -q '^nobody:' /etc/passwd && grep -q '^nogroup:' /etc/group
 then
-	chmod 666 *.gcda 2>/dev/null
-	cp rh rh2
-	chown nobody rh2
-	chgrp nogroup rh2
-	chmod 4755 rh2
-	test_rawhide_post_hook() { test_rh_errno_post_hook; }
-
-	if [ x"$asan" != x1 ] # ASAN doesn't work when setuid
+	if [ x"$asan" != x1 ] # ASAN doesn't work when setuid/setgid
 	then
+		chmod 666 *.gcda 2>/dev/null
+		cp rh rh2
+		chown nobody rh2
+		chgrp nogroup rh2
+		chmod 4755 rh2
+		test_rawhide_post_hook() { test_rh_errno_post_hook; }
+
 		test_rawhide "RAWHIDE_TEST_SETUID_FAILURE=1 ./rh2 -Nn -f rawhide.conf -M0 -X 'echo %S' -e exit $d" "" "./rh2: failed to revoke unexpected setuid privileges: Success\n" 1 "fail to revoke setuid privileges"
 
 		test_rawhide "./rh2 -Nn -f rawhide.conf -M0 -X 'echo %S' -e exit $d" ".$t\n" "" 0 "revoke setuid privileges (just for coverage)"
@@ -144,33 +144,33 @@ then
 
 			rm -r $d/otherd
 		fi
+
+		chmod 2755 rh2
+
+		test_rawhide "RAWHIDE_TEST_SETGID_FAILURE=1 ./rh2 -Nn -f rawhide.conf -M0 -X 'echo %S' -e exit $d" "" "./rh2: failed to revoke unexpected setgid privileges: Success\n" 1 "fail to revoke setgid privileges"
+
+		test_rawhide "./rh2 -Nn -f rawhide.conf -M0 -X 'echo %S' -e exit $d" ".$t\n" "" 0 "revoke setgid privileges (just for coverage)"
+
+		if grep -q '^daemon:' /etc/passwd && [ -x "`command -v sudo`" ]
+		then
+			mkdir $d/otherd
+			touch $d/otherd/otherf
+			chown nobody $d/otherd $d/otherd/otherf
+			chgrp nogroup $d/otherd $d/otherd/otherf
+			chmod 750 $d/otherd
+			chmod 644 $d/otherd/otherf
+
+			test_rawhide "               ./rh2 -Nn -f rawhide.conf $d/otherd" "$d/otherd\n$d/otherd/otherf\n" ""                                              0 "revoke setuid privileges (as root setuid nobody)"
+			test_rawhide "sudo -u daemon ./rh2 -Nn -f rawhide.conf $d/otherd" "$d/otherd\n"                   "./rh2: tests/.t19/otherd: Permission denied\n" 1 "revoke setuid privileges (as daemon setuid nobody)"
+
+			rm -r $d/otherd
+		fi
+
+		test_rawhide_post_hook() { true; }
+
+		rm rh2
+		chmod 644 *.gcda 2>/dev/null
 	fi
-
-	chmod 2755 rh2
-
-	test_rawhide "RAWHIDE_TEST_SETGID_FAILURE=1 ./rh2 -Nn -f rawhide.conf -M0 -X 'echo %S' -e exit $d" "" "./rh2: failed to revoke unexpected setgid privileges: Success\n" 1 "fail to revoke setgid privileges"
-
-	test_rawhide "./rh2 -Nn -f rawhide.conf -M0 -X 'echo %S' -e exit $d" ".$t\n" "" 0 "revoke setgid privileges (just for coverage)"
-
-	if grep -q '^daemon:' /etc/passwd && [ -x "`command -v sudo`" ]
-	then
-		mkdir $d/otherd
-		touch $d/otherd/otherf
-		chown nobody $d/otherd $d/otherd/otherf
-		chgrp nogroup $d/otherd $d/otherd/otherf
-		chmod 750 $d/otherd
-		chmod 644 $d/otherd/otherf
-
-		test_rawhide "               ./rh2 -Nn -f rawhide.conf $d/otherd" "$d/otherd\n$d/otherd/otherf\n" ""                                              0 "revoke setuid privileges (as root setuid nobody)"
-		test_rawhide "sudo -u daemon ./rh2 -Nn -f rawhide.conf $d/otherd" "$d/otherd\n"                   "./rh2: tests/.t19/otherd: Permission denied\n" 1 "revoke setuid privileges (as daemon setuid nobody)"
-
-		rm -r $d/otherd
-	fi
-
-	test_rawhide_post_hook() { true; }
-
-	rm rh2
-	chmod 644 *.gcda 2>/dev/null
 fi
 
 test_rawhide "$rh -M0 -x 'echo %%' $d" "%%\n" "" 0 "-x with %%"
