Add support for attr (file attributes) on Solaris

diff --git a/tests/t26 b/tests/t26
--- a/tests/t26
+++ b/tests/t26
@@ -836,62 +836,82 @@ then
 			rmdir $d/d
 			test_rawhide_post_hook() { true; }
 		fi
-	elif $rh -h | grep -wq attr # FreeBSD, OpenBSD, NetBSD, macOS
+	elif $rh -h | grep -wq attr # FreeBSD, OpenBSD, NetBSD, macOS, Solaris
 	then
-		if [ -n "`command -v chflags`" ]
-		then
-			case `sysctl -n kern.securelevel` in
-				-1|0)
-					test_rawhide_post_hook() { test_rh_sort_post_hook; }
-					mkdir $d/d
-					touch $d/f
-					ln -s d $d/ld
-					ln -s f $d/lf
-					# uappnd works on OpenBSD and NetBSD and macOS,
-					# but now fails on FreeBSD, but sappnd works on FreeBSD
-					if chflags uappnd $d/d $d/f 2>/dev/null
-					then
-						test_rawhide_grep "$rh -e 'd && attr & 0x00000004' -L '%p %e\n' $d" "$d/d .*append.*" "" 0 "-L %e (attribute) d"
-						test_rawhide_grep "$rh -e 'f && attr & 0x00000004' -L '%p %e\n' $d" "$d/f .*append.*" "" 0 "-L %e (attribute) f"
+		case "`uname`" in
+			SunOS|Solaris)
+				touch $d/f
+				chmod S+ci $d/f >/dev/null 2>/dev/null
+				if [ $? = 0 ]
+				then
+					test_rawhide_grep "$rh -e 'attr & 0x0020' -L '%p %e\n'   $d" "$d/f .*immutable.*" "" 0 "-L %e (attribute)"
 
-						test_rawhide_grep "$rh -e 'f && attr & 0x00000004' -L '%e\n'      $d/f" "^[^ ].*[^ ]$" "" 0 "-L '%e\\\\n' $d/f"
-						test_rawhide_grep "$rh -e 'f && attr & 0x00000004' -L '%15e\n'    $d/f" "^ +.+$"       "" 0 "-L '%15e\\\\n' $d/f"
-						test_rawhide_grep "$rh -e 'f && attr & 0x00000004' -L '%-15e\n'   $d/f" "^.+ +$"       "" 0 "-L '%-15e\\\\n' $d/f"
-						test_rawhide_grep "$rh -e 'f && attr & 0x00000004' -L '%15.5e\n'  $d/f" "^ +.....$"    "" 0 "-L '%15.5e\\\\n' $d/f"
-						test_rawhide_grep "$rh -e 'f && attr & 0x00000004' -L '%-15.5e\n' $d/f" "^..... +$"    "" 0 "-L '%-15.5e\\\\n' $d/f"
+					test_rawhide_grep "$rh -e 'attr & 0x0020' -L '%e\n'      $d/f" "^[^ ].*[^ ]$" "" 0 "-L '%e\\\\n' $d/f"
+					test_rawhide_grep "$rh -e 'attr & 0x0020' -L '%50e\n'    $d/f" "^ +.+$"       "" 0 "-L '%50e\\\\n' $d/f"
+					test_rawhide_grep "$rh -e 'attr & 0x0020' -L '%-50e\n'   $d/f" "^.+ +$"       "" 0 "-L '%-50e\\\\n' $d/f"
+					test_rawhide_grep "$rh -e 'attr & 0x0020' -L '%50.5e\n'  $d/f" "^ +.....$"    "" 0 "-L '%50.5e\\\\n' $d/f"
+					test_rawhide_grep "$rh -e 'attr & 0x0020' -L '%-50.5e\n' $d/f" "^..... +$"    "" 0 "-L '%-50.5e\\\\n' $d/f"
+					chmod S-ci $d/f
+				fi
+				rm $d/f
+				;;
+			*)
+				if [ -n "`command -v chflags`" ]
+				then
+					case `sysctl -n kern.securelevel` in
+						-1|0)
+							test_rawhide_post_hook() { test_rh_sort_post_hook; }
+							mkdir $d/d
+							touch $d/f
+							ln -s d $d/ld
+							ln -s f $d/lf
+							# uappnd works on OpenBSD and NetBSD and macOS,
+							# but now fails on FreeBSD, but sappnd works on FreeBSD
+							if chflags uappnd $d/d $d/f 2>/dev/null
+							then
+								test_rawhide_grep "$rh -e 'd && attr & 0x00000004' -L '%p %e\n' $d" "$d/d .*append.*" "" 0 "-L %e (attribute) d"
+								test_rawhide_grep "$rh -e 'f && attr & 0x00000004' -L '%p %e\n' $d" "$d/f .*append.*" "" 0 "-L %e (attribute) f"
 
-						# For test coverage
-						test_rawhide_grep "RAWHIDE_TEST_ATTR_FORMAT=1 $rh -e 'd && attr & 0x00000004' -L '%p %e\n' $d" "$d/d .*append.*" "" 0 "-L %e (attribute) d all attributes"
+								test_rawhide_grep "$rh -e 'f && attr & 0x00000004' -L '%e\n'      $d/f" "^[^ ].*[^ ]$" "" 0 "-L '%e\\\\n' $d/f"
+								test_rawhide_grep "$rh -e 'f && attr & 0x00000004' -L '%15e\n'    $d/f" "^ +.+$"       "" 0 "-L '%15e\\\\n' $d/f"
+								test_rawhide_grep "$rh -e 'f && attr & 0x00000004' -L '%-15e\n'   $d/f" "^.+ +$"       "" 0 "-L '%-15e\\\\n' $d/f"
+								test_rawhide_grep "$rh -e 'f && attr & 0x00000004' -L '%15.5e\n'  $d/f" "^ +.....$"    "" 0 "-L '%15.5e\\\\n' $d/f"
+								test_rawhide_grep "$rh -e 'f && attr & 0x00000004' -L '%-15.5e\n' $d/f" "^..... +$"    "" 0 "-L '%-15.5e\\\\n' $d/f"
 
-						chflags nouappnd $d/d $d/f
-					elif chflags sappend $d/d $d/f
-					then
-						test_rawhide_grep "$rh -e 'd && attr & 0x00040000' -L '%p %e\n' $d" "$d/d .*append.*" "" 0 "-L %e (attribute) d"
-						test_rawhide_grep "$rh -e 'f && attr & 0x00040000' -L '%p %e\n' $d" "$d/f .*append.*" "" 0 "-L %e (attribute) f"
+								# For test coverage
+								test_rawhide_grep "RAWHIDE_TEST_ATTR_FORMAT=1 $rh -e 'd && attr & 0x00000004' -L '%p %e\n' $d" "$d/d .*append.*" "" 0 "-L %e (attribute) d all attributes"
 
-						test_rawhide_grep "$rh -e 'f && attr & 0x00040000' -L '%e\n'      $d/f" "^[^ ].*[^ ]$" "" 0 "-L '%e\\\\n' $d/f"
-						test_rawhide_grep "$rh -e 'f && attr & 0x00040000' -L '%16e\n'    $d/f" "^ +.+$"       "" 0 "-L '%16e\\\\n' $d/f"
-						test_rawhide_grep "$rh -e 'f && attr & 0x00040000' -L '%-16e\n'   $d/f" "^.+ +$"       "" 0 "-L '%-16e\\\\n' $d/f"
-						test_rawhide_grep "$rh -e 'f && attr & 0x00040000' -L '%16.5e\n'  $d/f" "^ +.....$"    "" 0 "-L '%16.5e\\\\n' $d/f"
-						test_rawhide_grep "$rh -e 'f && attr & 0x00040000' -L '%-16.5e\n' $d/f" "^..... +$"    "" 0 "-L '%-16.5e\\\\n' $d/f"
+								chflags nouappnd $d/d $d/f
+							elif chflags sappend $d/d $d/f
+							then
+								test_rawhide_grep "$rh -e 'd && attr & 0x00040000' -L '%p %e\n' $d" "$d/d .*append.*" "" 0 "-L %e (attribute) d"
+								test_rawhide_grep "$rh -e 'f && attr & 0x00040000' -L '%p %e\n' $d" "$d/f .*append.*" "" 0 "-L %e (attribute) f"
 
-						# For test coverage
-						test_rawhide_grep "RAWHIDE_TEST_ATTR_FORMAT=1 $rh -e 'd && attr & 0x00040000' -L '%p %e\n' $d" "$d/d .*append.*" "" 0 "-L %e (attribute) d all attributes"
+								test_rawhide_grep "$rh -e 'f && attr & 0x00040000' -L '%e\n'      $d/f" "^[^ ].*[^ ]$" "" 0 "-L '%e\\\\n' $d/f"
+								test_rawhide_grep "$rh -e 'f && attr & 0x00040000' -L '%16e\n'    $d/f" "^ +.+$"       "" 0 "-L '%16e\\\\n' $d/f"
+								test_rawhide_grep "$rh -e 'f && attr & 0x00040000' -L '%-16e\n'   $d/f" "^.+ +$"       "" 0 "-L '%-16e\\\\n' $d/f"
+								test_rawhide_grep "$rh -e 'f && attr & 0x00040000' -L '%16.5e\n'  $d/f" "^ +.....$"    "" 0 "-L '%16.5e\\\\n' $d/f"
+								test_rawhide_grep "$rh -e 'f && attr & 0x00040000' -L '%-16.5e\n' $d/f" "^..... +$"    "" 0 "-L '%-16.5e\\\\n' $d/f"
 
-						chflags nouappnd $d/d $d/f
-					else
-						echo "$t: Skipping chflags tests (chflags uappnd/sappend failed)"
-					fi
+								# For test coverage
+								test_rawhide_grep "RAWHIDE_TEST_ATTR_FORMAT=1 $rh -e 'd && attr & 0x00040000' -L '%p %e\n' $d" "$d/d .*append.*" "" 0 "-L %e (attribute) d all attributes"
 
-					rm -f $d/ld $d/lf $d/f
-					rmdir $d/d
-					test_rawhide_post_hook() { true; }
-					;;
-				*)
-					echo "$t: Skipping chflags tests (kern.securelevel is too high)"
-					;;
-			esac
-		fi
+								chflags nouappnd $d/d $d/f
+							else
+								echo "$t: Skipping chflags tests (chflags uappnd/sappend failed)"
+							fi
+
+							rm -f $d/ld $d/lf $d/f
+							rmdir $d/d
+							test_rawhide_post_hook() { true; }
+							;;
+						*)
+							echo "$t: Skipping chflags tests (kern.securelevel is too high)"
+							;;
+					esac
+				fi
+				;;
+		esac
 	fi
 fi
 
